import type { PatternDef } from '../types.js';

// Ticks: 480 = quarter, 240 = eighth, 120 = sixteenth.
// Fingers: p on the bass strings, i/m/a on t3/t2/t1.

export const ARPEGGIO_PATTERNS: PatternDef[] = [
  {
    id: 'arpeggio.basic.roll',
    name: 'Simple roll',
    hint: 'One bass note, then the fingers roll up and back down the top three strings.',
    style: 'arpeggio',
    level: 'basic',
    meters: [3, 4],
    anchor: 'bar',
    events: {
      4: [
        { tick: 0, dur: 960, finger: 'p', target: 'bass' },
        { tick: 240, dur: 240, finger: 'i', target: 't3' },
        { tick: 480, dur: 240, finger: 'm', target: 't2' },
        { tick: 720, dur: 480, finger: 'a', target: 't1' },
        { tick: 960, dur: 240, finger: 'm', target: 't2' },
        { tick: 1200, dur: 240, finger: 'i', target: 't3' },
        { tick: 1440, dur: 240, finger: 'm', target: 't2' },
        { tick: 1680, dur: 240, finger: 'i', target: 't3' },
      ],
      3: [
        { tick: 0, dur: 960, finger: 'p', target: 'bass' },
        { tick: 240, dur: 240, finger: 'i', target: 't3' },
        { tick: 480, dur: 240, finger: 'm', target: 't2' },
        { tick: 720, dur: 480, finger: 'a', target: 't1' },
        { tick: 960, dur: 240, finger: 'm', target: 't2' },
        { tick: 1200, dur: 240, finger: 'i', target: 't3' },
      ],
    },
  },
  {
    id: 'arpeggio.basic.slow-roll',
    name: 'Slow roll',
    hint: 'One note per beat: thumb on the bass, then index, middle and ring up the strings.',
    style: 'arpeggio',
    level: 'basic',
    meters: [3, 4],
    anchor: 'bar',
    events: {
      4: [
        { tick: 0, dur: 1920, finger: 'p', target: 'bass' },
        { tick: 480, dur: 1440, finger: 'i', target: 't3' },
        { tick: 960, dur: 960, finger: 'm', target: 't2' },
        { tick: 1440, dur: 480, finger: 'a', target: 't1' },
      ],
      3: [
        { tick: 0, dur: 1440, finger: 'p', target: 'bass' },
        { tick: 480, dur: 960, finger: 'i', target: 't3' },
        { tick: 960, dur: 480, finger: 'm', target: 't2' },
      ],
    },
  },
  {
    id: 'arpeggio.moderate.pimami',
    name: 'p-i-m-a-m-i',
    hint: 'Thumb, then index, middle, ring and back down; the thumb moves to a second bass string at the end of the bar.',
    style: 'arpeggio',
    level: 'moderate',
    meters: [3, 4],
    anchor: 'bar',
    events: {
      4: [
        { tick: 0, dur: 960, finger: 'p', target: 'bass' },
        { tick: 240, dur: 240, finger: 'i', target: 't3' },
        { tick: 480, dur: 240, finger: 'm', target: 't2' },
        { tick: 720, dur: 480, finger: 'a', target: 't1' },
        { tick: 960, dur: 240, finger: 'm', target: 't2' },
        { tick: 1200, dur: 240, finger: 'i', target: 't3' },
        { tick: 1440, dur: 480, finger: 'p', target: 'altBass' },
        { tick: 1680, dur: 240, finger: 'i', target: 't3' },
      ],
      3: [
        { tick: 0, dur: 960, finger: 'p', target: 'bass' },
        { tick: 240, dur: 240, finger: 'i', target: 't3' },
        { tick: 480, dur: 240, finger: 'm', target: 't2' },
        { tick: 720, dur: 480, finger: 'a', target: 't1' },
        { tick: 960, dur: 240, finger: 'm', target: 't2' },
        { tick: 1200, dur: 240, finger: 'i', target: 't3' },
      ],
    },
  },
  {
    id: 'arpeggio.moderate.pami',
    name: 'p-a-m-i',
    hint: 'Thumb on the bass, then ring, middle and index down from the top string; the second half starts on the other bass string.',
    style: 'arpeggio',
    level: 'moderate',
    meters: [3, 4],
    anchor: 'bar',
    events: {
      4: [
        { tick: 0, dur: 960, finger: 'p', target: 'bass' },
        { tick: 240, dur: 240, finger: 'a', target: 't1' },
        { tick: 480, dur: 240, finger: 'm', target: 't2' },
        { tick: 720, dur: 240, finger: 'i', target: 't3' },
        { tick: 960, dur: 960, finger: 'p', target: 'altBass' },
        { tick: 1200, dur: 240, finger: 'a', target: 't1' },
        { tick: 1440, dur: 240, finger: 'm', target: 't2' },
        { tick: 1680, dur: 240, finger: 'i', target: 't3' },
      ],
      3: [
        { tick: 0, dur: 960, finger: 'p', target: 'bass' },
        { tick: 240, dur: 240, finger: 'a', target: 't1' },
        { tick: 480, dur: 240, finger: 'm', target: 't2' },
        { tick: 720, dur: 240, finger: 'i', target: 't3' },
        { tick: 960, dur: 480, finger: 'p', target: 'altBass' },
        { tick: 1200, dur: 240, finger: 'a', target: 't1' },
      ],
    },
  },
  // MUSIC-REVIEW: with the root on string 0 the alt bass is string 2, the same
  // string as t4, so the thumb repeats that note on the second half of the bar.
  {
    id: 'arpeggio.advanced.five-string',
    name: 'Five-string arpeggio',
    hint: 'Sixteenth notes: the thumb plays the bass and the 4th string, then index, middle and ring roll up and back. The bass moves each half bar.',
    style: 'arpeggio',
    level: 'advanced',
    meters: [3, 4],
    anchor: 'bar',
    events: {
      4: [
        { tick: 0, dur: 960, finger: 'p', target: 'bass', accent: true },
        { tick: 120, dur: 120, finger: 'p', target: 't4' },
        { tick: 240, dur: 120, finger: 'i', target: 't3' },
        { tick: 360, dur: 120, finger: 'm', target: 't2' },
        { tick: 480, dur: 240, finger: 'a', target: 't1' },
        { tick: 600, dur: 120, finger: 'm', target: 't2' },
        { tick: 720, dur: 120, finger: 'i', target: 't3' },
        { tick: 840, dur: 120, finger: 'p', target: 't4' },
        { tick: 960, dur: 960, finger: 'p', target: 'altBass' },
        { tick: 1080, dur: 120, finger: 'p', target: 't4' },
        { tick: 1200, dur: 120, finger: 'i', target: 't3' },
        { tick: 1320, dur: 120, finger: 'm', target: 't2' },
        { tick: 1440, dur: 240, finger: 'a', target: 't1' },
        { tick: 1560, dur: 120, finger: 'm', target: 't2' },
        { tick: 1680, dur: 120, finger: 'i', target: 't3' },
        { tick: 1800, dur: 120, finger: 'p', target: 't4' },
      ],
      3: [
        { tick: 0, dur: 720, finger: 'p', target: 'bass', accent: true },
        { tick: 120, dur: 120, finger: 'p', target: 't4' },
        { tick: 240, dur: 120, finger: 'i', target: 't3' },
        { tick: 360, dur: 120, finger: 'm', target: 't2' },
        { tick: 480, dur: 240, finger: 'a', target: 't1' },
        { tick: 600, dur: 120, finger: 'm', target: 't2' },
        { tick: 720, dur: 720, finger: 'p', target: 'altBass' },
        { tick: 840, dur: 120, finger: 'p', target: 't4' },
        { tick: 960, dur: 120, finger: 'i', target: 't3' },
        { tick: 1080, dur: 120, finger: 'm', target: 't2' },
        { tick: 1200, dur: 240, finger: 'a', target: 't1' },
        { tick: 1320, dur: 120, finger: 'm', target: 't2' },
      ],
    },
  },
  {
    id: 'arpeggio.advanced.giuliani',
    name: 'Giuliani figure',
    hint: 'Thumb and ring pinch on the beat, then index, middle, index. The bass moves on beat 3.',
    style: 'arpeggio',
    level: 'advanced',
    meters: [3, 4],
    anchor: 'bar',
    events: {
      4: [
        { tick: 0, dur: 960, finger: 'p', target: 'bass', tech: 'pinch', accent: true },
        { tick: 0, dur: 480, finger: 'a', target: 't1', tech: 'pinch', accent: true },
        { tick: 240, dur: 240, finger: 'i', target: 't3' },
        { tick: 480, dur: 240, finger: 'm', target: 't2' },
        { tick: 720, dur: 240, finger: 'i', target: 't3' },
        { tick: 960, dur: 960, finger: 'p', target: 'altBass', tech: 'pinch' },
        { tick: 960, dur: 480, finger: 'a', target: 't1', tech: 'pinch' },
        { tick: 1200, dur: 240, finger: 'i', target: 't3' },
        { tick: 1440, dur: 240, finger: 'm', target: 't2' },
        { tick: 1680, dur: 240, finger: 'i', target: 't3' },
      ],
      3: [
        { tick: 0, dur: 960, finger: 'p', target: 'bass', tech: 'pinch', accent: true },
        { tick: 0, dur: 480, finger: 'a', target: 't1', tech: 'pinch', accent: true },
        { tick: 240, dur: 240, finger: 'i', target: 't3' },
        { tick: 480, dur: 240, finger: 'm', target: 't2' },
        { tick: 720, dur: 240, finger: 'i', target: 't3' },
        { tick: 960, dur: 480, finger: 'p', target: 'altBass', tech: 'pinch' },
        { tick: 960, dur: 480, finger: 'a', target: 't1', tech: 'pinch' },
        { tick: 1200, dur: 240, finger: 'i', target: 't3' },
      ],
    },
  },
];
