import type { PatternDef } from '../types.js';

// Ticks: 480 = quarter, 240 = eighth.
// Fingers: p on the bass strings, i/m/a on t3/t2/t1.

export const FINGERSTYLE_PATTERNS: PatternDef[] = [
  {
    id: 'fingerstyle.basic.thumb-pluck',
    name: 'Thumb and pluck',
    hint: 'Thumb on the bass, then pluck the top three strings together.',
    style: 'fingerstyle',
    level: 'basic',
    meters: [3, 4],
    anchor: 'bar',
    moods: ['melancholic', 'warm'],
    events: {
      4: [
        { tick: 0, dur: 960, finger: 'p', target: 'bass' },
        { tick: 480, dur: 480, finger: 'i', target: 't3' },
        { tick: 480, dur: 480, finger: 'm', target: 't2' },
        { tick: 480, dur: 480, finger: 'a', target: 't1' },
        { tick: 960, dur: 960, finger: 'p', target: 'bass' },
        { tick: 1440, dur: 480, finger: 'i', target: 't3' },
        { tick: 1440, dur: 480, finger: 'm', target: 't2' },
        { tick: 1440, dur: 480, finger: 'a', target: 't1' },
      ],
      3: [
        { tick: 0, dur: 1440, finger: 'p', target: 'bass' },
        { tick: 480, dur: 480, finger: 'i', target: 't3' },
        { tick: 480, dur: 480, finger: 'm', target: 't2' },
        { tick: 480, dur: 480, finger: 'a', target: 't1' },
        { tick: 960, dur: 480, finger: 'i', target: 't3' },
        { tick: 960, dur: 480, finger: 'm', target: 't2' },
        { tick: 960, dur: 480, finger: 'a', target: 't1' },
      ],
    },
  },
  {
    id: 'fingerstyle.basic.thumb-pinch',
    name: 'Steady thumb and pinch',
    hint: 'The thumb plays the bass on every beat; pinch the top string with it on the strong beats.',
    style: 'fingerstyle',
    level: 'basic',
    meters: [3, 4],
    anchor: 'bar',
    moods: ['upbeat', 'intense'],
    events: {
      4: [
        { tick: 0, dur: 480, finger: 'p', target: 'bass', tech: 'pinch', accent: true },
        { tick: 0, dur: 960, finger: 'a', target: 't1', tech: 'pinch', accent: true },
        { tick: 480, dur: 480, finger: 'p', target: 'bass' },
        { tick: 960, dur: 480, finger: 'p', target: 'bass', tech: 'pinch' },
        { tick: 960, dur: 960, finger: 'a', target: 't1', tech: 'pinch' },
        { tick: 1440, dur: 480, finger: 'p', target: 'bass' },
      ],
      3: [
        { tick: 0, dur: 480, finger: 'p', target: 'bass', tech: 'pinch', accent: true },
        { tick: 0, dur: 1440, finger: 'a', target: 't1', tech: 'pinch', accent: true },
        { tick: 480, dur: 480, finger: 'p', target: 'bass' },
        { tick: 960, dur: 480, finger: 'p', target: 'bass' },
      ],
    },
  },
  {
    // M6b: Travis picking with a treble note on every thumb stroke, so it never thins to one note.
    // M7b: the thumb is palm-muted on the off-beat bass notes and the index hammers on once a bar,
    // so Moderate sounds different from Basic, not just busier.
    // MUSIC-REVIEW: 13 notes a bar, with a three-note pinch on beat 3, is busier than the other
    // moderate patterns. Check it's still moderate, not advanced, for a learner.
    id: 'fingerstyle.moderate.travis-pinch',
    name: 'Travis with pinches',
    hint: 'The thumb alternates bass strings on every beat and a finger plays with it each time; the other fingers fill the off-beats.',
    style: 'fingerstyle',
    level: 'moderate',
    meters: [3, 4],
    anchor: 'bar',
    moods: ['intense'],
    events: {
      4: [
        { tick: 0, dur: 480, finger: 'p', target: 'bass', tech: 'pinch', accent: true },
        { tick: 0, dur: 480, finger: 'm', target: 't1', tech: 'pinch', accent: true },
        { tick: 240, dur: 480, finger: 'i', target: 't2' },
        { tick: 480, dur: 240, finger: 'p', target: 'altBass', tech: 'palm-mute' },
        { tick: 480, dur: 480, finger: 'i', target: 't3' },
        { tick: 720, dur: 240, finger: 'm', target: 't1' },
        { tick: 960, dur: 480, finger: 'p', target: 'bass', tech: 'pinch' },
        { tick: 960, dur: 240, finger: 'i', target: 't3', tech: 'pinch' },
        { tick: 960, dur: 480, finger: 'a', target: 't1', tech: 'pinch' },
        { tick: 1200, dur: 480, finger: 'i', target: 't3', tech: 'hammer' },
        { tick: 1440, dur: 240, finger: 'p', target: 'altBass', tech: 'palm-mute' },
        { tick: 1440, dur: 240, finger: 'm', target: 't2' },
        { tick: 1680, dur: 240, finger: 'a', target: 't1' },
      ],
      3: [
        { tick: 0, dur: 480, finger: 'p', target: 'bass', tech: 'pinch', accent: true },
        { tick: 0, dur: 480, finger: 'm', target: 't1', tech: 'pinch', accent: true },
        { tick: 240, dur: 480, finger: 'i', target: 't2' },
        { tick: 480, dur: 240, finger: 'p', target: 'altBass', tech: 'palm-mute' },
        { tick: 480, dur: 480, finger: 'i', target: 't3' },
        { tick: 720, dur: 240, finger: 'm', target: 't1' },
        { tick: 960, dur: 480, finger: 'p', target: 'bass', tech: 'pinch' },
        { tick: 960, dur: 240, finger: 'i', target: 't3', tech: 'pinch' },
        { tick: 960, dur: 480, finger: 'a', target: 't1', tech: 'pinch' },
        { tick: 1200, dur: 240, finger: 'i', target: 't3', tech: 'hammer' },
      ],
    },
  },
  {
    // M11: brushes are fingerstyle strums, not a strumming style: they sit between the thumb's
    // bass notes and the tune stays on top.
    // MUSIC-REVIEW: brush on 2 and 4 with an up-flick on 4-and; check it isn't too busy under a tune.
    id: 'fingerstyle.moderate.thumb-brush',
    name: 'Thumb and brush',
    hint: 'The thumb plays the bass on 1 and 3; the index brushes down across the top strings on 2 and 4 and flicks back up after 4.',
    style: 'fingerstyle',
    level: 'moderate',
    meters: [3, 4],
    anchor: 'bar',
    moods: ['upbeat'],
    events: {
      4: [
        { tick: 0, dur: 480, finger: 'p', target: 'bass', tech: 'pinch', accent: true },
        { tick: 0, dur: 480, finger: 'm', target: 't1', tech: 'pinch', accent: true },
        { tick: 480, dur: 480, finger: 'i', target: 't3', tech: 'brush-down', accent: true },
        { tick: 480, dur: 480, finger: 'i', target: 't2', tech: 'brush-down', accent: true },
        { tick: 480, dur: 480, finger: 'i', target: 't1', tech: 'brush-down', accent: true },
        { tick: 960, dur: 480, finger: 'p', target: 'altBass' },
        { tick: 1200, dur: 240, finger: 'i', target: 't2' },
        { tick: 1440, dur: 240, finger: 'i', target: 't3', tech: 'brush-down', accent: true },
        { tick: 1440, dur: 240, finger: 'i', target: 't2', tech: 'brush-down', accent: true },
        { tick: 1440, dur: 240, finger: 'i', target: 't1', tech: 'brush-down', accent: true },
        { tick: 1680, dur: 240, finger: 'i', target: 't1', tech: 'brush-up' },
        { tick: 1680, dur: 240, finger: 'i', target: 't2', tech: 'brush-up' },
      ],
      3: [
        { tick: 0, dur: 480, finger: 'p', target: 'bass', tech: 'pinch', accent: true },
        { tick: 0, dur: 480, finger: 'm', target: 't1', tech: 'pinch', accent: true },
        { tick: 480, dur: 480, finger: 'i', target: 't3', tech: 'brush-down' },
        { tick: 480, dur: 480, finger: 'i', target: 't2', tech: 'brush-down' },
        { tick: 480, dur: 480, finger: 'i', target: 't1', tech: 'brush-down' },
        { tick: 960, dur: 240, finger: 'i', target: 't3', tech: 'brush-down' },
        { tick: 960, dur: 240, finger: 'i', target: 't2', tech: 'brush-down' },
        { tick: 960, dur: 240, finger: 'i', target: 't1', tech: 'brush-down' },
        { tick: 1200, dur: 240, finger: 'i', target: 't1', tech: 'brush-up' },
        { tick: 1200, dur: 240, finger: 'i', target: 't2', tech: 'brush-up' },
      ],
    },
  },
  {
    id: 'fingerstyle.moderate.travis',
    name: 'Travis picking',
    hint: 'The thumb alternates between two bass strings on every beat while the fingers fill the gaps.',
    style: 'fingerstyle',
    level: 'moderate',
    meters: [3, 4],
    anchor: 'bar',
    moods: ['upbeat', 'warm'],
    events: {
      4: [
        { tick: 0, dur: 480, finger: 'p', target: 'bass', tech: 'pinch', accent: true },
        { tick: 0, dur: 480, finger: 'm', target: 't1', tech: 'pinch', accent: true },
        { tick: 480, dur: 480, finger: 'p', target: 'altBass', tech: 'palm-mute' },
        { tick: 720, dur: 240, finger: 'i', target: 't2' },
        { tick: 960, dur: 480, finger: 'p', target: 'bass' },
        { tick: 1200, dur: 240, finger: 'm', target: 't1' },
        { tick: 1440, dur: 480, finger: 'p', target: 'altBass', tech: 'palm-mute' },
        { tick: 1680, dur: 240, finger: 'i', target: 't2' },
      ],
      3: [
        { tick: 0, dur: 480, finger: 'p', target: 'bass', tech: 'pinch', accent: true },
        { tick: 0, dur: 480, finger: 'm', target: 't1', tech: 'pinch', accent: true },
        { tick: 480, dur: 480, finger: 'p', target: 'altBass', tech: 'palm-mute' },
        { tick: 720, dur: 240, finger: 'i', target: 't2' },
        { tick: 960, dur: 480, finger: 'p', target: 'altBass', tech: 'palm-mute' },
        { tick: 1200, dur: 240, finger: 'm', target: 't1' },
      ],
    },
  },
  {
    id: 'fingerstyle.moderate.boom-chick',
    name: 'Alternating bass and chord',
    hint: 'The thumb alternates between two bass strings; index and middle pluck two strings together in between.',
    style: 'fingerstyle',
    level: 'moderate',
    meters: [3, 4],
    anchor: 'bar',
    moods: ['upbeat'],
    events: {
      4: [
        { tick: 0, dur: 480, finger: 'p', target: 'bass', accent: true },
        { tick: 480, dur: 480, finger: 'i', target: 't3' },
        { tick: 480, dur: 480, finger: 'm', target: 't2' },
        { tick: 960, dur: 480, finger: 'p', target: 'altBass', tech: 'palm-mute' },
        { tick: 1440, dur: 240, finger: 'i', target: 't3' },
        { tick: 1440, dur: 240, finger: 'm', target: 't2' },
        { tick: 1680, dur: 240, finger: 'a', target: 't1' },
      ],
      3: [
        { tick: 0, dur: 480, finger: 'p', target: 'bass', accent: true },
        { tick: 480, dur: 480, finger: 'i', target: 't3' },
        { tick: 480, dur: 480, finger: 'm', target: 't2' },
        { tick: 960, dur: 240, finger: 'p', target: 'altBass', tech: 'palm-mute' },
        { tick: 1200, dur: 240, finger: 'm', target: 't2' },
        { tick: 1200, dur: 240, finger: 'a', target: 't1' },
      ],
    },
  },
  {
    // M10: a calm fingerstyle for slow, dark songs: rolls that ring, one hammer-on, no palm mute.
    // MUSIC-REVIEW: tagged melancholic/warm; check it reads as a ballad, not as an arpeggio exercise.
    id: 'fingerstyle.moderate.ballad',
    name: 'Ballad roll',
    hint: 'Thumb and ring together, then index, middle and index roll gently; the thumb moves on beat 3, and the middle finger hammers on near the end.',
    style: 'fingerstyle',
    level: 'moderate',
    meters: [3, 4],
    anchor: 'bar',
    moods: ['melancholic', 'warm'],
    events: {
      4: [
        { tick: 0, dur: 960, finger: 'p', target: 'bass', tech: 'pinch', accent: true },
        { tick: 0, dur: 960, finger: 'a', target: 't1', tech: 'pinch', accent: true },
        { tick: 240, dur: 720, finger: 'i', target: 't3' },
        { tick: 480, dur: 480, finger: 'm', target: 't2' },
        { tick: 720, dur: 240, finger: 'i', target: 't3' },
        { tick: 960, dur: 960, finger: 'p', target: 'altBass' },
        { tick: 1200, dur: 480, finger: 'm', target: 't2' },
        { tick: 1440, dur: 480, finger: 'a', target: 't1' },
        { tick: 1680, dur: 240, finger: 'm', target: 't2', tech: 'hammer' },
      ],
      3: [
        { tick: 0, dur: 960, finger: 'p', target: 'bass', tech: 'pinch', accent: true },
        { tick: 0, dur: 1440, finger: 'a', target: 't1', tech: 'pinch', accent: true },
        { tick: 240, dur: 1200, finger: 'i', target: 't3' },
        { tick: 480, dur: 960, finger: 'm', target: 't2' },
        { tick: 720, dur: 240, finger: 'a', target: 't1' },
        { tick: 960, dur: 480, finger: 'p', target: 'altBass' },
        { tick: 1200, dur: 240, finger: 'm', target: 't2' },
      ],
    },
  },
  {
    // M7b: percussive Travis. The thumb slaps on 2 and 4 instead of plucking, the index
    // hammers on and pulls off, and the bar ends on a bell-like harmonic.
    // MUSIC-REVIEW: the harmonic on the last eighth needs the fretting hand to lift for a
    // moment (the runner drops it when a fretted note sounds with it). Check it reads as a
    // flourish, not a stumble, at faster tempos.
    id: 'fingerstyle.advanced.travis-hammer',
    name: 'Percussive Travis',
    hint: 'Thumb on the bass on 1 and 3 and a thumb slap on 2 and 4; the index hammers on and pulls off, and each bar ends on a harmonic.',
    style: 'fingerstyle',
    level: 'advanced',
    meters: [3, 4],
    anchor: 'chord',
    moods: ['intense'],
    events: {
      4: [
        { tick: 0, dur: 480, finger: 'p', target: 'bass', tech: 'pinch', accent: true },
        { tick: 0, dur: 240, finger: 'm', target: 't1', tech: 'pinch', accent: true },
        { tick: 240, dur: 240, finger: 'i', target: 't3' },
        { tick: 480, dur: 120, finger: 'p', target: 'all', tech: 'slap', accent: true },
        { tick: 480, dur: 240, finger: 'i', target: 't3', tech: 'hammer' },
        { tick: 720, dur: 240, finger: 'm', target: 't2' },
        { tick: 960, dur: 480, finger: 'p', target: 'altBass', tech: 'pinch' },
        { tick: 960, dur: 240, finger: 'm', target: 't1', tech: 'pinch' },
        { tick: 1200, dur: 240, finger: 'i', target: 't3' },
        { tick: 1440, dur: 120, finger: 'p', target: 'all', tech: 'slap', accent: true },
        { tick: 1440, dur: 240, finger: 'i', target: 't3', tech: 'pull' },
        { tick: 1680, dur: 240, finger: 'a', target: 't1', tech: 'harmonic' },
      ],
      3: [
        { tick: 0, dur: 480, finger: 'p', target: 'bass', tech: 'pinch', accent: true },
        { tick: 0, dur: 240, finger: 'm', target: 't1', tech: 'pinch', accent: true },
        { tick: 240, dur: 240, finger: 'i', target: 't3' },
        { tick: 480, dur: 120, finger: 'p', target: 'all', tech: 'slap', accent: true },
        { tick: 480, dur: 240, finger: 'i', target: 't3', tech: 'hammer' },
        { tick: 720, dur: 240, finger: 'm', target: 't2' },
        { tick: 960, dur: 240, finger: 'p', target: 'altBass', tech: 'palm-mute' },
        { tick: 960, dur: 240, finger: 'i', target: 't3' },
        { tick: 1200, dur: 240, finger: 'a', target: 't1', tech: 'harmonic' },
      ],
    },
  },
  {
    // M11: a pop fingerstyle groove: the thumb and fingers pick sixteenths around brushes on 2
    // and 4, the up-brush lifting the off-beat.
    // MUSIC-REVIEW: the 16th pickup on the thumb (beat 4-a) may crowd fast songs.
    id: 'fingerstyle.advanced.pop-groove',
    name: 'Pop groove',
    hint: 'Pick the bass and top string on 1, brush down on 2 and 4 with a flick up after each, and let the thumb walk on 3.',
    style: 'fingerstyle',
    level: 'advanced',
    meters: [3, 4],
    anchor: 'bar',
    moods: ['upbeat'],
    events: {
      4: [
        { tick: 0, dur: 480, finger: 'p', target: 'bass', tech: 'pinch', accent: true },
        { tick: 0, dur: 480, finger: 'a', target: 't1', tech: 'pinch', accent: true },
        { tick: 240, dur: 240, finger: 'i', target: 't2' },
        { tick: 480, dur: 240, finger: 'i', target: 't3', tech: 'brush-down', accent: true },
        { tick: 480, dur: 240, finger: 'i', target: 't2', tech: 'brush-down', accent: true },
        { tick: 480, dur: 240, finger: 'i', target: 't1', tech: 'brush-down', accent: true },
        { tick: 720, dur: 240, finger: 'i', target: 't1', tech: 'brush-up' },
        { tick: 720, dur: 240, finger: 'i', target: 't2', tech: 'brush-up' },
        { tick: 960, dur: 360, finger: 'p', target: 'altBass' },
        { tick: 1200, dur: 120, finger: 'i', target: 't2' },
        { tick: 1320, dur: 120, finger: 'm', target: 't1' },
        { tick: 1440, dur: 240, finger: 'i', target: 't3', tech: 'brush-down', accent: true },
        { tick: 1440, dur: 240, finger: 'i', target: 't2', tech: 'brush-down', accent: true },
        { tick: 1440, dur: 240, finger: 'i', target: 't1', tech: 'brush-down', accent: true },
        { tick: 1680, dur: 120, finger: 'i', target: 't1', tech: 'brush-up' },
        { tick: 1680, dur: 120, finger: 'i', target: 't2', tech: 'brush-up' },
        { tick: 1800, dur: 120, finger: 'p', target: 'bass' },
      ],
      3: [
        { tick: 0, dur: 480, finger: 'p', target: 'bass', tech: 'pinch', accent: true },
        { tick: 0, dur: 480, finger: 'a', target: 't1', tech: 'pinch', accent: true },
        { tick: 240, dur: 240, finger: 'i', target: 't2' },
        { tick: 480, dur: 240, finger: 'i', target: 't3', tech: 'brush-down', accent: true },
        { tick: 480, dur: 240, finger: 'i', target: 't2', tech: 'brush-down', accent: true },
        { tick: 480, dur: 240, finger: 'i', target: 't1', tech: 'brush-down', accent: true },
        { tick: 720, dur: 240, finger: 'i', target: 't1', tech: 'brush-up' },
        { tick: 720, dur: 240, finger: 'i', target: 't2', tech: 'brush-up' },
        { tick: 960, dur: 240, finger: 'p', target: 'altBass' },
        { tick: 1200, dur: 120, finger: 'i', target: 't2' },
        { tick: 1320, dur: 120, finger: 'm', target: 't1' },
      ],
    },
  },
  {
    id: 'fingerstyle.advanced.syncopated',
    name: 'Syncopated Travis',
    hint: 'Pinches land off the beat while the thumb keeps time, with a hammer-on early in each bar.',
    style: 'fingerstyle',
    level: 'advanced',
    meters: [3, 4],
    anchor: 'chord',
    moods: ['upbeat'],
    events: {
      4: [
        { tick: 0, dur: 480, finger: 'p', target: 'bass', tech: 'pinch', accent: true },
        { tick: 0, dur: 240, finger: 'm', target: 't1', tech: 'pinch', accent: true },
        { tick: 240, dur: 240, finger: 'i', target: 't3' },
        { tick: 480, dur: 480, finger: 'p', target: 'altBass', tech: 'palm-mute' },
        { tick: 480, dur: 240, finger: 'i', target: 't3', tech: 'hammer' },
        { tick: 720, dur: 480, finger: 'i', target: 't2', accent: true },
        { tick: 720, dur: 480, finger: 'm', target: 't1', accent: true },
        { tick: 960, dur: 480, finger: 'p', target: 'bass' },
        { tick: 1200, dur: 240, finger: 'i', target: 't3' },
        { tick: 1440, dur: 480, finger: 'p', target: 'altBass', tech: 'palm-mute' },
        { tick: 1440, dur: 240, finger: 'i', target: 't2' },
        { tick: 1680, dur: 240, finger: 'm', target: 't1', accent: true },
      ],
      3: [
        { tick: 0, dur: 480, finger: 'p', target: 'bass', tech: 'pinch', accent: true },
        { tick: 0, dur: 240, finger: 'm', target: 't1', tech: 'pinch', accent: true },
        { tick: 240, dur: 240, finger: 'i', target: 't3' },
        { tick: 480, dur: 480, finger: 'p', target: 'altBass', tech: 'palm-mute' },
        { tick: 480, dur: 240, finger: 'i', target: 't3', tech: 'hammer' },
        { tick: 720, dur: 480, finger: 'i', target: 't2', accent: true },
        { tick: 720, dur: 480, finger: 'm', target: 't1', accent: true },
        { tick: 960, dur: 480, finger: 'p', target: 'altBass', tech: 'palm-mute' },
        { tick: 1200, dur: 240, finger: 'm', target: 't1', accent: true },
      ],
    },
  },
  {
    // M10: the calm Advanced fingerstyle: sixteenth rolls with ligados and a harmonic, no slaps.
    // MUSIC-REVIEW: same harmonic caveat as Percussive Travis.
    id: 'fingerstyle.advanced.ballad',
    name: 'Ballad with ligados',
    hint: 'Gentle sixteenth rolls over a thumb on 1 and 3, a hammer-on and a pull-off in each half, and a harmonic to end the bar.',
    style: 'fingerstyle',
    level: 'advanced',
    meters: [3, 4],
    anchor: 'bar',
    moods: ['melancholic', 'warm'],
    events: {
      4: [
        { tick: 0, dur: 960, finger: 'p', target: 'bass', tech: 'pinch', accent: true },
        { tick: 0, dur: 480, finger: 'a', target: 't1', tech: 'pinch', accent: true },
        { tick: 240, dur: 240, finger: 'i', target: 't3' },
        { tick: 360, dur: 240, finger: 'm', target: 't2' },
        { tick: 480, dur: 240, finger: 'i', target: 't3', tech: 'hammer' },
        { tick: 720, dur: 240, finger: 'm', target: 't2' },
        { tick: 960, dur: 960, finger: 'p', target: 'altBass', tech: 'pinch' },
        { tick: 960, dur: 240, finger: 'm', target: 't2', tech: 'pinch' },
        { tick: 1200, dur: 240, finger: 'i', target: 't3' },
        { tick: 1320, dur: 120, finger: 'm', target: 't2', tech: 'pull' },
        { tick: 1440, dur: 240, finger: 'a', target: 't1' },
        { tick: 1680, dur: 240, finger: 'a', target: 't1', tech: 'harmonic' },
      ],
      3: [
        { tick: 0, dur: 960, finger: 'p', target: 'bass', tech: 'pinch', accent: true },
        { tick: 0, dur: 480, finger: 'a', target: 't1', tech: 'pinch', accent: true },
        { tick: 240, dur: 240, finger: 'i', target: 't3' },
        { tick: 360, dur: 240, finger: 'm', target: 't2' },
        { tick: 480, dur: 240, finger: 'i', target: 't3', tech: 'hammer' },
        { tick: 720, dur: 240, finger: 'm', target: 't2' },
        { tick: 960, dur: 480, finger: 'p', target: 'altBass' },
        { tick: 1200, dur: 240, finger: 'a', target: 't1', tech: 'harmonic' },
      ],
    },
  },
];
