import type { PatternDef } from '../types.js';

// Ticks: 480 = quarter, 240 = eighth.
// Fingers: p on the bass strings, i/m/a on t3/t2/t1.

export const FINGERSTYLE_PATTERNS: PatternDef[] = [
  {
    id: 'fingerstyle.basic.thumb-pluck',
    name: 'Thumb and pluck',
    hint: 'Thumb on the bass, then pluck the top three strings together.',
    style: 'fingerstyle',
    level: 'basic',
    meters: [3, 4],
    anchor: 'bar',
    events: {
      4: [
        { tick: 0, dur: 960, finger: 'p', target: 'bass' },
        { tick: 480, dur: 480, finger: 'i', target: 't3' },
        { tick: 480, dur: 480, finger: 'm', target: 't2' },
        { tick: 480, dur: 480, finger: 'a', target: 't1' },
        { tick: 960, dur: 960, finger: 'p', target: 'bass' },
        { tick: 1440, dur: 480, finger: 'i', target: 't3' },
        { tick: 1440, dur: 480, finger: 'm', target: 't2' },
        { tick: 1440, dur: 480, finger: 'a', target: 't1' },
      ],
      3: [
        { tick: 0, dur: 1440, finger: 'p', target: 'bass' },
        { tick: 480, dur: 480, finger: 'i', target: 't3' },
        { tick: 480, dur: 480, finger: 'm', target: 't2' },
        { tick: 480, dur: 480, finger: 'a', target: 't1' },
        { tick: 960, dur: 480, finger: 'i', target: 't3' },
        { tick: 960, dur: 480, finger: 'm', target: 't2' },
        { tick: 960, dur: 480, finger: 'a', target: 't1' },
      ],
    },
  },
  {
    id: 'fingerstyle.basic.thumb-pinch',
    name: 'Steady thumb and pinch',
    hint: 'The thumb plays the bass on every beat; pinch the top string with it on the strong beats.',
    style: 'fingerstyle',
    level: 'basic',
    meters: [3, 4],
    anchor: 'bar',
    events: {
      4: [
        { tick: 0, dur: 480, finger: 'p', target: 'bass', tech: 'pinch', accent: true },
        { tick: 0, dur: 960, finger: 'a', target: 't1', tech: 'pinch', accent: true },
        { tick: 480, dur: 480, finger: 'p', target: 'bass' },
        { tick: 960, dur: 480, finger: 'p', target: 'bass', tech: 'pinch' },
        { tick: 960, dur: 960, finger: 'a', target: 't1', tech: 'pinch' },
        { tick: 1440, dur: 480, finger: 'p', target: 'bass' },
      ],
      3: [
        { tick: 0, dur: 480, finger: 'p', target: 'bass', tech: 'pinch', accent: true },
        { tick: 0, dur: 1440, finger: 'a', target: 't1', tech: 'pinch', accent: true },
        { tick: 480, dur: 480, finger: 'p', target: 'bass' },
        { tick: 960, dur: 480, finger: 'p', target: 'bass' },
      ],
    },
  },
  {
    // M6b: Travis picking with a treble note on every thumb stroke, so it never thins to one note.
    // MUSIC-REVIEW: 13 notes a bar, with a three-note pinch on beat 3, is busier than the other
    // moderate patterns. Check it's still moderate, not advanced, for a learner.
    id: 'fingerstyle.moderate.travis-pinch',
    name: 'Travis with pinches',
    hint: 'The thumb alternates bass strings on every beat and a finger plays with it each time; the other fingers fill the off-beats.',
    style: 'fingerstyle',
    level: 'moderate',
    meters: [3, 4],
    anchor: 'bar',
    events: {
      4: [
        { tick: 0, dur: 480, finger: 'p', target: 'bass', tech: 'pinch', accent: true },
        { tick: 0, dur: 480, finger: 'm', target: 't1', tech: 'pinch', accent: true },
        { tick: 240, dur: 480, finger: 'i', target: 't2' },
        { tick: 480, dur: 480, finger: 'p', target: 'altBass', tech: 'pinch' },
        { tick: 480, dur: 480, finger: 'i', target: 't3', tech: 'pinch' },
        { tick: 720, dur: 240, finger: 'm', target: 't1' },
        { tick: 960, dur: 480, finger: 'p', target: 'bass', tech: 'pinch' },
        { tick: 960, dur: 480, finger: 'm', target: 't2', tech: 'pinch' },
        { tick: 960, dur: 480, finger: 'a', target: 't1', tech: 'pinch' },
        { tick: 1200, dur: 240, finger: 'i', target: 't3' },
        { tick: 1440, dur: 480, finger: 'p', target: 'altBass', tech: 'pinch' },
        { tick: 1440, dur: 240, finger: 'm', target: 't2', tech: 'pinch' },
        { tick: 1680, dur: 240, finger: 'a', target: 't1' },
      ],
      3: [
        { tick: 0, dur: 480, finger: 'p', target: 'bass', tech: 'pinch', accent: true },
        { tick: 0, dur: 480, finger: 'm', target: 't1', tech: 'pinch', accent: true },
        { tick: 240, dur: 480, finger: 'i', target: 't2' },
        { tick: 480, dur: 480, finger: 'p', target: 'altBass', tech: 'pinch' },
        { tick: 480, dur: 480, finger: 'i', target: 't3', tech: 'pinch' },
        { tick: 720, dur: 240, finger: 'm', target: 't1' },
        { tick: 960, dur: 480, finger: 'p', target: 'bass', tech: 'pinch' },
        { tick: 960, dur: 480, finger: 'm', target: 't2', tech: 'pinch' },
        { tick: 960, dur: 480, finger: 'a', target: 't1', tech: 'pinch' },
        { tick: 1200, dur: 240, finger: 'i', target: 't3' },
      ],
    },
  },
  {
    id: 'fingerstyle.moderate.travis',
    name: 'Travis picking',
    hint: 'The thumb alternates between two bass strings on every beat while the fingers fill the gaps.',
    style: 'fingerstyle',
    level: 'moderate',
    meters: [3, 4],
    anchor: 'bar',
    events: {
      4: [
        { tick: 0, dur: 480, finger: 'p', target: 'bass', tech: 'pinch', accent: true },
        { tick: 0, dur: 480, finger: 'm', target: 't1', tech: 'pinch', accent: true },
        { tick: 480, dur: 480, finger: 'p', target: 'altBass' },
        { tick: 720, dur: 240, finger: 'i', target: 't2' },
        { tick: 960, dur: 480, finger: 'p', target: 'bass' },
        { tick: 1200, dur: 240, finger: 'm', target: 't1' },
        { tick: 1440, dur: 480, finger: 'p', target: 'altBass' },
        { tick: 1680, dur: 240, finger: 'i', target: 't2' },
      ],
      3: [
        { tick: 0, dur: 480, finger: 'p', target: 'bass', tech: 'pinch', accent: true },
        { tick: 0, dur: 480, finger: 'm', target: 't1', tech: 'pinch', accent: true },
        { tick: 480, dur: 480, finger: 'p', target: 'altBass' },
        { tick: 720, dur: 240, finger: 'i', target: 't2' },
        { tick: 960, dur: 480, finger: 'p', target: 'altBass' },
        { tick: 1200, dur: 240, finger: 'm', target: 't1' },
      ],
    },
  },
  {
    id: 'fingerstyle.moderate.boom-chick',
    name: 'Alternating bass and chord',
    hint: 'The thumb alternates between two bass strings; index and middle pluck two strings together in between.',
    style: 'fingerstyle',
    level: 'moderate',
    meters: [3, 4],
    anchor: 'bar',
    events: {
      4: [
        { tick: 0, dur: 480, finger: 'p', target: 'bass', accent: true },
        { tick: 480, dur: 480, finger: 'i', target: 't3' },
        { tick: 480, dur: 480, finger: 'm', target: 't2' },
        { tick: 960, dur: 480, finger: 'p', target: 'altBass' },
        { tick: 1440, dur: 240, finger: 'i', target: 't3' },
        { tick: 1440, dur: 240, finger: 'm', target: 't2' },
        { tick: 1680, dur: 240, finger: 'a', target: 't1' },
      ],
      3: [
        { tick: 0, dur: 480, finger: 'p', target: 'bass', accent: true },
        { tick: 480, dur: 480, finger: 'i', target: 't3' },
        { tick: 480, dur: 480, finger: 'm', target: 't2' },
        { tick: 960, dur: 240, finger: 'p', target: 'altBass' },
        { tick: 1200, dur: 240, finger: 'm', target: 't2' },
        { tick: 1200, dur: 240, finger: 'a', target: 't1' },
      ],
    },
  },
  {
    id: 'fingerstyle.advanced.travis-hammer',
    name: 'Travis with hammer-ons',
    hint: 'Steady alternating thumb, pinches on the downbeats and a hammer-on early in each bar.',
    style: 'fingerstyle',
    level: 'advanced',
    meters: [3, 4],
    anchor: 'chord',
    events: {
      4: [
        { tick: 0, dur: 480, finger: 'p', target: 'bass', tech: 'pinch', accent: true },
        { tick: 0, dur: 240, finger: 'm', target: 't1', tech: 'pinch', accent: true },
        { tick: 240, dur: 240, finger: 'i', target: 't3' },
        { tick: 480, dur: 480, finger: 'p', target: 'altBass' },
        { tick: 480, dur: 240, finger: 'i', target: 't3', tech: 'hammer' },
        { tick: 720, dur: 240, finger: 'i', target: 't2' },
        { tick: 960, dur: 480, finger: 'p', target: 'bass', tech: 'pinch' },
        { tick: 960, dur: 240, finger: 'm', target: 't1', tech: 'pinch' },
        { tick: 1200, dur: 240, finger: 'i', target: 't3' },
        { tick: 1440, dur: 480, finger: 'p', target: 'altBass' },
        { tick: 1680, dur: 240, finger: 'i', target: 't2' },
      ],
      3: [
        { tick: 0, dur: 480, finger: 'p', target: 'bass', tech: 'pinch', accent: true },
        { tick: 0, dur: 240, finger: 'm', target: 't1', tech: 'pinch', accent: true },
        { tick: 240, dur: 240, finger: 'i', target: 't3' },
        { tick: 480, dur: 480, finger: 'p', target: 'altBass' },
        { tick: 480, dur: 240, finger: 'i', target: 't3', tech: 'hammer' },
        { tick: 720, dur: 240, finger: 'i', target: 't2' },
        { tick: 960, dur: 480, finger: 'p', target: 'altBass', tech: 'pinch' },
        { tick: 960, dur: 240, finger: 'm', target: 't1', tech: 'pinch' },
        { tick: 1200, dur: 240, finger: 'i', target: 't3' },
      ],
    },
  },
  {
    id: 'fingerstyle.advanced.syncopated',
    name: 'Syncopated Travis',
    hint: 'Pinches land off the beat while the thumb keeps time, with a hammer-on early in each bar.',
    style: 'fingerstyle',
    level: 'advanced',
    meters: [3, 4],
    anchor: 'chord',
    events: {
      4: [
        { tick: 0, dur: 480, finger: 'p', target: 'bass', tech: 'pinch', accent: true },
        { tick: 0, dur: 240, finger: 'm', target: 't1', tech: 'pinch', accent: true },
        { tick: 240, dur: 240, finger: 'i', target: 't3' },
        { tick: 480, dur: 480, finger: 'p', target: 'altBass' },
        { tick: 480, dur: 240, finger: 'i', target: 't3', tech: 'hammer' },
        { tick: 720, dur: 480, finger: 'i', target: 't2', accent: true },
        { tick: 720, dur: 480, finger: 'm', target: 't1', accent: true },
        { tick: 960, dur: 480, finger: 'p', target: 'bass' },
        { tick: 1200, dur: 240, finger: 'i', target: 't3' },
        { tick: 1440, dur: 480, finger: 'p', target: 'altBass' },
        { tick: 1440, dur: 240, finger: 'i', target: 't2' },
        { tick: 1680, dur: 240, finger: 'm', target: 't1', accent: true },
      ],
      3: [
        { tick: 0, dur: 480, finger: 'p', target: 'bass', tech: 'pinch', accent: true },
        { tick: 0, dur: 240, finger: 'm', target: 't1', tech: 'pinch', accent: true },
        { tick: 240, dur: 240, finger: 'i', target: 't3' },
        { tick: 480, dur: 480, finger: 'p', target: 'altBass' },
        { tick: 480, dur: 240, finger: 'i', target: 't3', tech: 'hammer' },
        { tick: 720, dur: 480, finger: 'i', target: 't2', accent: true },
        { tick: 720, dur: 480, finger: 'm', target: 't1', accent: true },
        { tick: 960, dur: 480, finger: 'p', target: 'altBass' },
        { tick: 1200, dur: 240, finger: 'm', target: 't1', accent: true },
      ],
    },
  },
];
